### ISSUE TITLE
Error when trying to use simple example bot

### ISSUE THREAD

**Issue by xonmello** [whatisaphone/rlbot-rust#13]
I am trying to run the example bot but I get `Error: StringError("RLBot did not become initialized")` every time. I have opened rocket league with -rlbot flag (online features are disabled), run the RLBot injector, and typed in the simple example `cargo run --example simple`. I thought this latest update would fix it but I tried with the latest version and I still can't get it to work.

**Comment by xonmello** [comment]
I tested and it works when typing in the command
`cargo build --example bot && python -c "from rlbot import runner; runner.main()"`

**Comment by naturecodevoid** [comment]
Maybe a `run.bat` should be made for this.

**Comment by xonmello** [comment]
The problem is the command that works requires python rlbot to be installed. I do not want this to be the case for my bot for easy testing purposes. I wonder if @whatisaphone is a phone has any ideas for why I am getting that original error.

**Comment by naturecodevoid** [comment]
This is true, but I don't think there is a very good way to do this other than the way you described, or installing the RLBot package into this repository, and running `cargo build --example bot && python -c "from rlbot import runner; runner.main()"` using the local RLBot.

**Comment by xonmello** [comment]
What I am saying is `cargo run --example simple` should work as it is in [the documentation](https://docs.rs/rlbot/0.5.0/rlbot/) but it is giving me an error even when adding the `-rlbot` flag.

**Comment by naturecodevoid** [comment]
It says there that you still need the RLBot PyPi package. I'm not sure, but try doing a double dash when you're launching (`Steam.exe -applaunch 252950 --rlbot`)

**Comment by xonmello** [comment]
Double flag doesn't work and leaves online play available. That isn't surprising though since steam flags are usually only a single dash.

**Comment by naturecodevoid** [comment]
Ok. I feel like RL is launched also with a second flag, but I can't remember.

**Comment by xonmello** [comment]
I also remember a second flag when doing python bot stuff at one point but I don't quite remember what it was. I guess we can just leave this issue open until that gets figured out... If you have some extra time at your computer you could download the example bot and see if you can get it to work on your computer.

**Comment by naturecodevoid** [comment]
I am working on a Python bot(and off to a pretty bad start) right now, and I can open steam and relaunch RL to try to figure the second flag out.

Another thought is that this should be in a batch file, like `run-framework.bat` like Java has.

**Comment by naturecodevoid** [comment]
Huh. It seems that Rocket League is run regularly?

https://github.com/RLBot/RLBot/blob/master/src/main/python/rlbot/setup_manager.py#L94-L110

**Comment by naturecodevoid** [comment]
And then the dll is injected, which makes it go offline?

**Comment by xonmello** [comment]
Launching with the -rlbot flag is what causes rocket league to only be available in offline mode. I have tried both with the dll injector and without and it doesn’t work either way. There is no noticeable difference between the dll being injected and not. I messaged Phone on discord and he will take a look at this when he gets a chance.

**Comment by naturecodevoid** [comment]
Ok.

**Comment by whatisaphone** [comment]
If `examples/bot` works but not `examples/simple`, I'm guessing the problem is a paths issue. Is it possible you have more than one copy of the RLBot DLLs on your system left over from testing/old versions?

For `examples/simple`, when you run RLBot.exe, it should open a console with debug output. Does it output the line `Signaling that interface dlls may begin communicating.`?

>Huh. It seems that Rocket League is run regularly?

That's outdated code. Unfortunately the RLBot/RLBot repo is no longer kept up to date with the actual source (for now, maybe). You should look at what you get from `pip install` to see the actual source.

**Comment by naturecodevoid** [comment]
Ah. Thanks for the tip.

**Comment by naturecodevoid** [comment]
I found the code that launches it, and the `IDEAL_ARGS` are `-rlbot` and `-nomovie`.

**Comment by xonmello** [comment]
My bot is not working. I am using the python framework but that isn't a big deal in reality.
