### ISSUE TITLE
Simple example doesn't open Rocket league

### ISSUE THREAD

**Issue by bgourlie** [whatisaphone/rlbot-rust#8]
I've downloaded the necessary EXE and DLL's and put them on my path, and when running the simple example it will not open Rocket League. If I manually open rocket league while the example is running, it will open a new match with no players and nothing happens. I've confirmed that the RLBot_Injector.exe process is running after starting the example. Is there anything obvious that I'm missing?

**Comment by whatisaphone** [comment]
This crate doesn't launch the game, you need to do that yourself. If you launch the game first, and then run the example, it should work.

I could probably clarify that in the docs. I'll leave this open for a bit to remind myself

**Comment by whatisaphone** [comment]
Feel free to re-open if you're still having trouble!
